name: mkdocs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
      - run: npm i
      - run: echo ${{github.repository}}
      - run: npm run docs:deploy
